version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    volumes:
      - ./.docker/mysql/config:/etc/mysql/conf
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 20181209
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    build:
      context: ./.docker/redis
    ports:
      - "6379:6379"
  go:
    container_name: go
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./server:/go/src/20181209sun-go-jwt/server
    ports:
      - "9000:9000"
    environment:
      GO111MODULE: "on"
    depends_on:
      - redis
      - mysql
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
    volumes:
      - ./.docker/nginx/logs:/var/log/nginx
      - ./client/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    depends_on:
      - go

volumes:
  dbdata: